gestionmateriales/gestionmateriales/Controllers/StockController.cs
using System.Linq;
using System.Web.Mvc;
using System.Web.Routing;
using System;
using gestionmateriales.Models.OficinaTecnica;
using gestionmateriales.Models.OficinaTecnica.GestionMateriales;
using gestionmateriales.Models.OficinaTecnica.Tipos;
using System.Data.Entity;
using System.Collections.Generic;
using gestionmateriales.Repository.Contracts;
using gestionmateriales.Repository.Implementation;
using gestionmateriales.Models.OficinaTecnica.Documentos;

namespace gestionmateriales.Controllers
{
    [Authorize(Roles = "administrador, oficinatecnica, deposito, compras")]
    [Route("/Stock")]
    public class StockController : Controller
    {
        private readonly ISalidaMaterialRepository salidaMaterialRepository;
        private readonly IEntradaMaterialRepository entradaMaterialRepository;
        private readonly IMaterialRepository materialRepository;
        private readonly ITipoEntradaMaterialRepository tipoEntradaMaterialRepository;
        private readonly ITipoSalidaMaterialRepository tipoSalidaMaterialRepository;
        private readonly IOrdenCompraRepository ordenCompraRepository;
        private readonly IOrdenTrabajoAplicacionRepository ordenTrabajoAplicacionRepository;
        private readonly IOrdenTrabajoRepository ordenTrabajoRepository;

        public StockController()
        {
            OficinaTecnicaEntities context = new OficinaTecnicaEntities();
            entradaMaterialRepository = new EntradaMaterialRepository(context);
            salidaMaterialRepository = new SalidaMaterialRepository(context);
            materialRepository = new MaterialRepository(context);
            tipoEntradaMaterialRepository = new TipoEntradaMaterialRepository(context);
            tipoSalidaMaterialRepository = new TipoSalidaMaterialRepository(context);
            ordenCompraRepository = new OrdenCompraRepository(context);
            ordenTrabajoAplicacionRepository = new OrdenTrabajoAplicacionRepository(context);
            ordenTrabajoRepository = new OrdenTrabajoRepository(context);
        }
        
        [HttpGet]
        public ActionResult Sumar()
        {
            cargarTipoEntrada();

            return View("Sumar");
        }

        [HttpPost]
        public ActionResult Sumar(EntradaMaterial unaEntrada)
        {
            var unMaterial = materialRepository.FindOne(x => x.codigo == unaEntrada.codigoMaterial && x.hab);

            if (unMaterial == null) throw new Exception("No existe el material");

            TipoEntradaMaterial unTipoEntrada = tipoEntradaMaterialRepository.FindById(unaEntrada.idTipoEntradaMaterial);

            if (unTipoEntrada == null) throw new Exception("No existe el tipo entrada material");

            if (!verificarMaterialenDocumento(unMaterial, unaEntrada, unTipoEntrada))
            {
                ViewBag.Result = 1;
                cargarTipoEntrada();
                return View("Sumar");
            }

            try
            {
                unMaterial.stockActual += unaEntrada.cantidad;

                EntradaMaterial nuevaEntrada = new EntradaMaterial()
                {
                    fecha = DateTime.Now,
                    codigoDocumento = unaEntrada.codigoDocumento,
                    codigoMaterial = unMaterial.codigo,
                    cantidad = unaEntrada.cantidad,
                    material = unMaterial,
                    tipoEntradaMaterial = unTipoEntrada,

                    CREATED_BY = User.Identity.Name,
                    CREATION_DATE = DateTime.Now,
                    CREATION_IP = Request.UserHostAddress,
                    LAST_UPDATED_BY = User.Identity.Name,
                    LAST_UPDATED_DATE = DateTime.Now,
                    LAST_UPDATED_IP = Request.UserHostAddress,
                };

                entradaMaterialRepository.Add(nuevaEntrada);
            }
            catch
            {
                return RedirectToAction("Error500", "Error");
            }

            ViewBag.Result = 0;

            cargarTipoEntrada();

            return View("Sumar");
        }

        private bool verificarMaterialenDocumento(Material unMaterial, EntradaMaterial unaEntrada, TipoEntradaMaterial unTipoEntrada)
        {
            int documento = Convert.ToInt32(unaEntrada.codigoDocumento);

            switch (unTipoEntrada.idTipoEntradaMaterial)
            {
                // Orden de Compra
                case 3:
                    {
                        OrdenCompra oc = ordenCompraRepository.FindOne(x => x.numeroInterno == documento);
                        if (oc == null) return false;
                        return oc.itemsOC.Any(x => x.material.idMaterial == unMaterial.idMaterial);
                    }
                // Orden de trabajo de aplicacion
                case 4:
                    {
                        OrdenTrabajoAplicacion ota = ordenTrabajoAplicacionRepository.FindOne(x => x.numero == documento);
                        if (ota == null) return false;
                        return ota.itemsOTA.Any(x => x.material.idMaterial == unMaterial.idMaterial);
                    }
                //case 8:
                //    {
                //        OrdenTrabajo ot = ordenTrabajoRepository.FindOne(x => x.numero == documento);
                //        return ot.itemsOT.Any(x => x.material.idMaterial == unMaterial.idMaterial);
                //    }
            }
            return true;
        }

        [HttpGet]
        public ActionResult Restar()
        {
            cargarTipoSalida();

            return View("Restar");
        }

        [HttpPost]
        public ActionResult Restar(SalidaMaterial unaSalida)
        {
            OficinaTecnicaEntities db = new OficinaTecnicaEntities();

            Material unMaterial = db.materiales
                   .Where(x => x.codigo == unaSalida.codigoMaterial && x.hab)
                   .Include(x => x.proveedor)
                   .Include(x => x.tipoMaterial)
                   .Include(x => x.unidad)
                   .Include(x => x.entradas)
                   .Include(x => x.salidas)
                   .FirstOrDefault();

            TipoSalidaMaterial unTipoSalida = db.tipoSalida.Find(unaSalida.idTipoSalidaMaterial);

            int cantidadMaximaRetirar = cantidadARetirarSegunDocumento(unMaterial, unaSalida, unTipoSalida);

            try
            {
                SalidaMaterial nuevaSalida = new SalidaMaterial()
                {
                    fecha = DateTime.Now,
                    material = unMaterial,
                    codigoMaterial = unMaterial.codigo,
                    codigoDocumento = unaSalida.codigoDocumento,
                    cantidad = unaSalida.cantidad,
                    tipoSalidaMaterial = unTipoSalida,

                    CREATED_BY = User.Identity.Name,
                    CREATION_DATE = DateTime.Now,
                    CREATION_IP = Request.UserHostAddress,
                    LAST_UPDATED_BY = User.Identity.Name,
                    LAST_UPDATED_DATE = DateTime.Now,
                    LAST_UPDATED_IP = Request.UserHostAddress
                };

                if (nuevaSalida.HayStock(cantidadMaximaRetirar))
                {
                    nuevaSalida.RestarStockMaterial();
                    db.salidas.Add(nuevaSalida);
                    db.SaveChanges();
                }
                else
                {
                    ViewBag.Result = 1;
                    cargarTipoSalida();
                    return View("Restar");
                }
            }
            catch
            {
                return RedirectToAction("Error500", "Error");
            }
            ViewBag.Result = 0;
            cargarTipoSalida();
            return View("Restar");
        }

        private int cantidadARetirarSegunDocumento(Material unMaterial, SalidaMaterial unaSalida, TipoSalidaMaterial unTipoSalidaMaterial)
        {
            int documento = Convert.ToInt32(unaSalida.codigoDocumento);

            switch (unTipoSalidaMaterial.idTipoSalidaMaterial)
            {
                // Orden de trabajo de aplicacion
                case 2:
                    {
                        OrdenTrabajoAplicacion ota = ordenTrabajoAplicacionRepository.FindOne(x => x.numero == documento);
                        int totalARetirar = ota.itemsOTA.FirstOrDefault(x => x.material.idMaterial == unMaterial.idMaterial).cantidad;
                        int retirado = salidaMaterialRepository.Find(x => x.codigoDocumento == unaSalida.codigoDocumento && x.material.idMaterial == unMaterial.idMaterial).Sum(x => x.cantidad);
                        return totalARetirar - retirado;
                    }
                // Orden de trabajo
                //case 3:
                //    {
                //        OrdenTrabajo ot = ordenTrabajoRepository.FindOne(x => x.numero == documento);
                //        return ot.itemsOT.FirstOrDefault(x => x.material.idMaterial == unMaterial.idMaterial).cantidad;
                //    }
            }
            return unMaterial.stockActual;
        }

        [HttpGet]
        public ActionResult HistorialIngresos()
        {
            return View("HistorialIngresos");
        }

        [HttpGet]
        public JsonResult GetHistorialEgresos()
        {
            var historialEgresos = from egr in salidaMaterialRepository.FindAll()
                                   select new
                                   {
                                       numero = egr.idSalidaMaterial,
                                       codMaterial = egr.codigoMaterial,
                                       material = egr.material.nombre,

gestionmateriales/gestionmateriales/Views/Stock/HistorialEgresos.cshtml
<div class="card shadow">
    <div class="card-body">
        <div class="row">
            <div class="col-6">
                <h1>Historial Salidas</h1>
            </div>
            <div class="offset-4 col-2">
                <a class="btn btn-outline-secondary btn-block" role="button" href="~/Home" title="Regresa a pantalla anterior"><i class="far fa-arrow-alt-to-left"></i> Volver</a>
            </div>
        </div>
        <p>Registro de las últimas salidas de materiales o herramientas de depósito</p>

    </div>
</div>
<br />
<div class="card shadow">
    <div id="divgrdEgresos" class="card-body">        
    </div>
</div>

<script type="text/javascript" src="~/Scripts/MasterDataTables.js"></script>
<script type="text/javascript" src="~/Scripts/Views/Stock/HistorialEgresos.js"></script>

gestionmateriales/gestionmateriales/Views/Stock/HistorialIngresos.cshtml
<div class="card shadow">
    <div class="card-body">
        <div class="row">
            <div class="col-6">
                <h1>Historial Entradas</h1>
            </div>
            <div class="offset-4 col-2">
                <a class="btn btn-outline-secondary btn-block" role="button" href="~/Home" title="Regresa a pantalla anterior"><i class="far fa-arrow-alt-to-left"></i> Volver</a>
            </div>
        </div>
        <p>Registro de las últimas entradas de materiales o herramientas a depósito</p>
    </div>
</div>
<br />
<div class="card shadow">
    <div id="divgrdIngresos" class="card-body">       
    </div>
</div>

<script type="text/javascript" src="~/Scripts/MasterDataTables.js"></script>
<script type="text/javascript" src="~/Scripts/Views/Stock/HistorialIngresos.js"></script>

gestionmateriales/gestionmateriales/Views/Stock/Restar.cshtml
@model gestionmateriales.Models.OficinaTecnica.GestionMateriales.SalidaMaterial
<div class="card shadow">
    <div class="card-body">
<h1>Salida</h1>
<p>Engreso de material o herramientas del depósito</p>
</div>
    </div>
<br />
<div class="card shadow">
    <div class="card-body">
        @using (@Html.BeginForm("Restar", "Stock", FormMethod.Post))
        {
            <div class="form row">
                <div class="form-group col-6">
                    <label for="companyValue">Código: </label>  <strong><span class="output" id="codigoMaterial"></span></strong>
                    <br />
                    <br />
                    <label for="materialPicker">Buscar Material o Herramienta </label><input type="text" id="materialPicker" name="material" class="form-control" autocomplete="off">
                    @* Aqui se guarda el codigo del material que se enviara en el formulario *@
                    @Html.EditorFor(model => model.codigoMaterial, new { htmlAttributes = new { @class = "form-control", id = "codMaterial", type = "hidden" } })
                </div>
                <div class="form-group col-6">
                    @Html.LabelFor(model => model.cantidad, "Cantidad a Egresar", new { @class = "control-label" })
                    @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control", min = 0, required = "true", id = "cantidadMaterial", autocomplete = "off" } })
                    <br />
                    @Html.LabelFor(model => model.tipoSalidaMaterial, "Tipo de Engreso", new { @class = "control-label" })
                    @Html.DropDownList("IdTipoSalidaMaterial", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form row">
                <div class="form-group offset-6 col-6">
                    @Html.LabelFor(model => model.codigoDocumento, "Número Documento", new { @class = "control-label" })
                    @Html.EditorFor(model => model.codigoDocumento, new { htmlAttributes = new { @class = "form-control", maxlength = 15, id = "codigoDocumento", required = "true", autocomplete = "off" } })
                </div>
            </div>
            <br />
            <div class="row">
                <div class="offset-8 col-md-2">
                    <input id="btn_aceptar" type="submit" class="btn btn-primary btn-block" value="Aceptar" title="Confirma la operación" />
                </div>
                <div class="col-md-2">
                    <a class="btn btn-outline-secondary btn-block" role="button" href="~/Home" title="Regresa a pantalla anterior"><i class="far fa-arrow-alt-to-left"></i> Volver</a>
                </div>
            </div>
        }

        @if (ViewBag.Result == 0)
        {
            <script type="text/javascript">
                $('#cantidadMaterial').val('');
                $('#codigoMaterial').text('');
                $('#codigoDocumento').val('');
                ShowNotificationSuccess('Stock');
            </script>
        }
        @if (ViewBag.Result == 1)
        {
            <script type="text/javascript">
                ShowNotificationDanger('Stock', 'No hay suficiente stock del material o la cantidad a retirar excede el limite establecido');
            </script>
        }

        <link rel="stylesheet" href="~/Scripts/Fuse/css/fuzzycomplete.min.css">
        <script type="text/javascript" src="~/Scripts/Fuse/fuse.min.js"></script>
        <script type="text/javascript" src="~/Scripts/Fuse/js/fuzzycomplete.min.js"></script>
        <script type="text/javascript" src="~/Scripts/Views/Stock/Stock.js"></script>
    </div>
</div>

gestionmateriales/gestionmateriales/Views/Stock/Sumar.cshtml
@model gestionmateriales.Models.OficinaTecnica.GestionMateriales.EntradaMaterial
<div class="card shadow">
    <div class="card-body">
<h1>Entrada</h1>
<p>Ingreso material o herramientas al stock del depósito</p>
</div>
    </div>
<br />
<div class="card shadow">
    <div class="card-body">
        @using (@Html.BeginForm("Sumar", "Stock", FormMethod.Post))
        {
            <div class="form row">
                <div class="form-group col-6">
                    <label for="companyValue">Código: </label>  <strong><span class="output" id="codigoMaterial"></span></strong>
                    <br />
                    <br />
                    <label for="materialPicker">Buscar Material o Herramienta </label><input type="text" id="materialPicker" name="material" class="form-control" autocomplete="off">
                    @* Aqui se guarda el codigo del material que se enviara en el formulario *@
                    @Html.EditorFor(model => model.codigoMaterial, new { htmlAttributes = new { @class = "form-control", id = "codMaterial", type = "hidden" } })
                </div>
                <div class="form-group col-6">
                    @Html.LabelFor(model => model.cantidad, "Cantidad a Ingresar", new { @class = "control-label" })
                    @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control", min = 0, required = "true", id = "cantidadMaterial", autocomplete = "off" } })
                    <br />
                    @Html.LabelFor(model => model.tipoEntradaMaterial, "Tipo de Entrada", new { @class = "control-label" })
                    @Html.DropDownList("IdTipoEntradaMaterial", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form row">
                <div class="form-group offset-6 col-6">
                    @Html.LabelFor(model => model.codigoDocumento, "Código Documento", new { @class = "control-label" })
                    @Html.EditorFor(model => model.codigoDocumento, new { htmlAttributes = new { @class = "form-control", maxlength = 15, required = "true", id = "codigoDocumento", autocomplete = "off" } })
                </div>
            </div>
            <br />
            <div class="row">
                <div class="offset-8 col-md-2">
                    <input id="btn_aceptar" type="submit" class="btn btn-primary btn-block" value="Aceptar" title="Confirma la operación" />
                </div>
                <div class="col-md-2">
                    <a class="btn btn-outline-secondary btn-block" role="button" href="~/Home" title="Regresa a pantalla anterior"><i class="far fa-arrow-alt-to-left"></i> Volver</a>
                </div>
            </div>
        }

        @if (ViewBag.Result == 0)
        {

            <script type="text/javascript">
                $('#cantidadMaterial').val('');
                $('#codigoMaterial').text('');
                $('#codigoDocumento').val('');
                ShowNotificationSuccess('Stock');
            </script>
        }
        @if (ViewBag.Result == 1)
        {
            <script type="text/javascript">
                ShowNotificationDanger('Stock', 'El tipo de documento y el número no existen');
            </script>
        }

        <link rel="stylesheet" href="~/Scripts/Fuse/css/fuzzycomplete.min.css">
        <script type="text/javascript" src="~/Scripts/Fuse/fuse.min.js"></script>
        <script type="text/javascript" src="~/Scripts/Fuse/js/fuzzycomplete.min.js"></script>
        <script type="text/javascript" src="~/Scripts/Views/Stock/Stock.js"></script>
    </div>
</div>